# 1.LSA 간단 실습

In [15]:
import numpy as np
import pandas as pd

## 1.DTM 행렬 생성

In [16]:
A = np.array([[0,0,0,1,0,1,1,0,0],
              [0,0,0,1,1,0,1,0,0],
              [0,1,1,0,2,0,0,0,0],
              [1,0,0,0,0,0,0,1,1]])
print('DTM의 크기(shape) :', np.shape(A))
display(A)

DTM의 크기(shape) : (4, 9)


array([[0, 0, 0, 1, 0, 1, 1, 0, 0],
       [0, 0, 0, 1, 1, 0, 1, 0, 0],
       [0, 1, 1, 0, 2, 0, 0, 0, 0],
       [1, 0, 0, 0, 0, 0, 0, 1, 1]])

## 2.Full SVD

In [17]:
# full_matrices = True : U = mxm, VT = nxn 크기로 만들겠다는 의미
# full_matrices = False : U 와 V의 크기는 최소한의 크기로 줄이겠다는 의미  ->  메모리와 계산 시간을 절약하기 위함
U, s, VT = np.linalg.svd(A, full_matrices=True)

- U

In [18]:
print(U.shape)
print(U.round(2))

(4, 4)
[[-0.24  0.75  0.   -0.62]
 [-0.51  0.44 -0.    0.74]
 [-0.83 -0.49 -0.   -0.27]
 [-0.   -0.    1.    0.  ]]


- S
- linalg.svd()는 특이값 분해의 결과로 대각 행렬이 아닌 특이값의 리스트를 반환 따라서 다시 대각 행렬로 변환 해주어야 함.
- np.diag()는 1차원 array는 각각의 값을 대각 성분으로 가지는 대각 행렬 생성, 2차원은 대각 성분의 값을 추출

In [19]:
print(s)
print(s.shape)
type(s)

[2.68731789 2.04508425 1.73205081 0.77197992]
(4,)


numpy.ndarray

In [20]:
np.diag(s)    # 대각행렬 생성 메서드로 array 를 입력값으로 받아들임

array([[2.68731789, 0.        , 0.        , 0.        ],
       [0.        , 2.04508425, 0.        , 0.        ],
       [0.        , 0.        , 1.73205081, 0.        ],
       [0.        , 0.        , 0.        , 0.77197992]])

In [21]:
# 대각 행렬의 크기인 4 x 9의 임의의 행렬 생성
S = np.zeros((4,9))
print(S)
print()

# 특이값을 대각행렬에 삽입
S[:4, :4]
print(S.round(2))
print(S.shape)

[[0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]]

[[0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]]
(4, 9)


- VT

In [22]:
print(VT.round(2))
print(VT.shape)

[[-0.   -0.31 -0.31 -0.28 -0.8  -0.09 -0.28 -0.   -0.  ]
 [ 0.   -0.24 -0.24  0.58 -0.26  0.37  0.58 -0.   -0.  ]
 [ 0.58 -0.    0.    0.   -0.    0.   -0.    0.58  0.58]
 [ 0.   -0.35 -0.35  0.16  0.25 -0.8   0.16 -0.   -0.  ]
 [-0.   -0.78 -0.01 -0.2   0.4   0.4  -0.2   0.    0.  ]
 [-0.29  0.31 -0.78 -0.24  0.23  0.23  0.01  0.14  0.14]
 [-0.29 -0.1   0.26 -0.59 -0.08 -0.08  0.66  0.14  0.14]
 [-0.5  -0.06  0.15  0.24 -0.05 -0.05 -0.19  0.75 -0.25]
 [-0.5  -0.06  0.15  0.24 -0.05 -0.05 -0.19 -0.25  0.75]]
(9, 9)


- U X S X VT = A
- np.allclose() : 두 배열이 거의 같은지 확인

In [23]:
np.allclose(A, np.dot(np.dot(U, S), VT).round(2))

False

## 3.Truncated SVD

In [25]:
# 특이값 상위 2개만 보존
S = S[:2,:2]

print(S.round(2))

[[0. 0.]
 [0. 0.]]


In [24]:
print(U.shape)
U = U[:,:2]
print(U.shape)
print(U)

(4, 4)
(4, 2)
[[-2.39751712e-01  7.51083898e-01]
 [-5.06077194e-01  4.44029376e-01]
 [-8.28495619e-01 -4.88580485e-01]
 [-8.78352025e-17 -2.98807451e-17]]


In [29]:
print(VT.shape)

VT = VT[:2, :]
print(VT.shape)
print(VT.round(2))

(2, 9)
(2, 9)
[[-0.   -0.31 -0.31 -0.28 -0.8  -0.09 -0.28 -0.   -0.  ]
 [ 0.   -0.24 -0.24  0.58 -0.26  0.37  0.58 -0.   -0.  ]]


In [31]:
A_prime = np.dot(np.dot(U,S), VT)
print(A)
print(A_prime.round(2))
print()
print(A.shape)
print(A_prime.shape)

[[0 0 0 1 0 1 1 0 0]
 [0 0 0 1 1 0 1 0 0]
 [0 1 1 0 2 0 0 0 0]
 [1 0 0 0 0 0 0 1 1]]
[[0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]]

(4, 9)
(4, 9)


## 4.sklearn TruncatedSVD 활용

In [34]:
from sklearn.decomposition import TruncatedSVD
# TruncatedSVD 객체 생성
svd_model = TruncatedSVD(n_components=2, algorithm='randomized', random_state=42)

# 문서-토픽 행렬 생성 UxS
lsa_matrix = svd_model.fit_transform(A)

# 단어-토픽 행렬 (components_) VT
components = svd_model.components_


- **fit_transform**은 문서-토픽 행렬을 반환. U x S\
      - 행(n_samples): 이 행렬의 각 행은 하나의 문서를 나타냄.\
      - 열(n_components): 이 행렬의 각 열은 하나의 토픽(축소된 차원)을 나타냄.\
      - 각 값: 특정 문서가 특정 토픽에서 얼마나 설명되는지를 나타냄. 값이 클수록 그 문서가 해당 토픽에서 더 잘 설명된다는 의미.\

- **components_**는 토픽-단어 행렬. S x VT\
      - 행(n_components): 토픽을 나타냄.\
      - 열(n_features): 단어를 나타냄.\
      - 각 값: 특정 토픽에서 특정 단어의 가중치(기여도)를 나타냄.\



In [35]:
# 출력
print("LSA 변환 결과 (문서 x 토픽 행렬):")
print(lsa_matrix)

print("LSA 변환 결과 (토픽 x 단어 행렬):")
print(components)

# 원래 행렬 근사
A_prime = np.dot(lsa_matrix, components)
print("\n근사된 행렬 (A_prime):")
print(A_prime.round(2))

LSA 변환 결과 (문서 x 토픽 행렬):
[[ 6.44289063e-01  1.53602985e+00]
 [ 1.35999029e+00  9.08077483e-01]
 [ 2.22643109e+00 -9.99188254e-01]
 [-4.58923455e-16  1.57281088e-16]]
LSA 변환 결과 (토픽 x 단어 행렬):
[[-1.18279879e-16  3.08298331e-01  3.08298331e-01  2.77536539e-01
   8.04917216e-01  8.92159849e-02  2.77536539e-01 -1.70321788e-16
  -1.70321788e-16]
 [-3.54655479e-17 -2.38904821e-01 -2.38904821e-01  5.84383395e-01
  -2.60689306e-01  3.67263060e-01  5.84383395e-01  9.63733179e-17
   9.63733179e-17]]

근사된 행렬 (A_prime):
[[-0.   -0.17 -0.17  1.08  0.12  0.62  1.08  0.    0.  ]
 [-0.    0.2   0.2   0.91  0.86  0.45  0.91 -0.   -0.  ]
 [-0.    0.93  0.93  0.03  2.05 -0.17  0.03 -0.   -0.  ]
 [ 0.   -0.   -0.   -0.   -0.    0.   -0.    0.    0.  ]]


In [42]:
a_prime_df = pd.DataFrame(A_prime.round(2))

# 2.뉴스 데이터를 통한 LSA 분석
- 사이킷런에서는 Twenty Newsgroups이라고 불리는 20개의 다른 주제를 가진 뉴스그룹 데이터를 제공

## 1.필요 모듈 로드

In [44]:
import pandas as pd
from sklearn.datasets import fetch_20newsgroups
from nltk.corpus import stopwords
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.decomposition import TruncatedSVD

## 2.데이터 로드

In [49]:
# 18000개의 문서로 이루어진 데이터셋 로그
dataset = fetch_20newsgroups(
    shuffle = True,                             # 데이터를 섞어서 로드 -> 데이터의 순서가 주는 영향을 방지하기 위함
    random_state = 1,
    remove = ('headers', 'footers', 'quotes')    # 헤더, 푸터, 인용문 등을 제거 -> 분류작업에 유용하지 않을 가능성이 높은 텍스트 요소 제거
)

documents = dataset.data
print('샘플 수: ', len(documents))


샘플 수:  11314


In [50]:
documents[:5]

["Well i'm not sure about the story nad it did seem biased. What\nI disagree with is your statement that the U.S. Media is out to\nruin Israels reputation. That is rediculous. The U.S. media is\nthe most pro-israeli media in the world. Having lived in Europe\nI realize that incidences such as the one described in the\nletter have occured. The U.S. media as a whole seem to try to\nignore them. The U.S. is subsidizing Israels existance and the\nEuropeans are not (at least not to the same degree). So I think\nthat might be a reason they report more clearly on the\natrocities.\n\tWhat is a shame is that in Austria, daily reports of\nthe inhuman acts commited by Israeli soldiers and the blessing\nreceived from the Government makes some of the Holocaust guilt\ngo away. After all, look how the Jews are treating other races\nwhen they got power. It is unfortunate.\n",
 "\n\n\n\n\n\n\nYeah, do you expect people to read the FAQ, etc. and actually accept hard\natheism?  No, you need a little leap

In [52]:
# 뉴스 토픽 확인

print(dataset.target_names)
print('카테고리 수 : ', len(dataset.target_names))

['alt.atheism', 'comp.graphics', 'comp.os.ms-windows.misc', 'comp.sys.ibm.pc.hardware', 'comp.sys.mac.hardware', 'comp.windows.x', 'misc.forsale', 'rec.autos', 'rec.motorcycles', 'rec.sport.baseball', 'rec.sport.hockey', 'sci.crypt', 'sci.electronics', 'sci.med', 'sci.space', 'soc.religion.christian', 'talk.politics.guns', 'talk.politics.mideast', 'talk.politics.misc', 'talk.religion.misc']
카테고리 수 :  20


## 3.데이터 전처리
  1. 대문자->소문자
  2. 구두점, 숫자, 특수 문자 제거
  3. 짧은 단어 제거

- [^a-zA-Z] : 영문자를 제외한 모든 문자
- regrex=True : 함수에서 이 패턴을 정규 표현식으로 처리
- ' '.join([w for w in x.split() if len(w)>3]) : 데이터를 순회하면서 공백으로 단어를 나누고 길이가 3이상인 단어들을 리스트로 반환하고 join 함수를 통해서 한 줄의 텍스트로 병합

In [54]:
news_df = pd.DataFrame({'documents': documents})
news_df.head()

documents
0  Well i'm not sure about the story nad it did s...
1  \n\n\n\n\n\n\nYeah, do you expect people to re...
2  Although I realize that principle is not one o...
3  Notwithstanding all the legitimate fuss about ...
4  Well, I will have to change the scoring on my ...

In [56]:
# 특수 문자 제거
news_df['clean_doc'] = news_df['documents'].str.replace('[^a-zA-Z]', " ", regex = True)

# 길이가 3이하인 단어는 제거 (길이가 짧은 단어 제거)
news_df['clean_doc'] = news_df['clean_doc'].apply(lambda x: ' '.join([w for w in  x.split() if len(w) > 3]))

# 전체 단어에 대한 소문자 변환
news_df['clean_doc'] = news_df['clean_doc'].apply(lambda x: x.lower())

In [57]:
news_df.head(10)

documents  \
0  Well i'm not sure about the story nad it did s...   
1  \n\n\n\n\n\n\nYeah, do you expect people to re...   
2  Although I realize that principle is not one o...   
3  Notwithstanding all the legitimate fuss about ...   
4  Well, I will have to change the scoring on my ...   
5   \n \nI read somewhere, I think in Morton Smit...   
6  \nOk.  I have a record that shows a IIsi with ...   
7  \n\n\nSounds like wishful guessing.\n\n\n\n\n'...   
8   Nobody is saying that you shouldn't be allowe...   
9  \n  I was wondering if anyone can shed any lig...   

                                           clean_doc  
0  well sure about story seem biased what disagre...  
1  yeah expect people read actually accept hard a...  
2  although realize that principle your strongest...  
3  notwithstanding legitimate fuss about this pro...  
4  well will have change scoring playoff pool unf...  
5  read somewhere think morton smith jesus magici...  
6  have record that shows iisi with without cache...  
7  sounds like wishful guessing called what mean ...  
8  nobody saying that shouldn allowed just force ...  
9  wondering anyone shed light just that these el...

## 4.TF-IDF 벡터화

- stop_words='english' : 불용어 사전, sklearn에서 제공하는 기본 영어 불용어 리스트
- max_features=1000 : 상위 1000개의 단어만을 보존
- max_df=0.5 : 너무 자주 등장하는 경우 해당 단어를 무시. 50% 이상 나타나는 단어는 무시
- smooth_idf=True : IDF 점수 계산 시, smoothing을 적용.
  - 스무딩은 IDF 계산에서 모든 문서에 1을 더하는 방식으로, IDF 값이 0이 되는 것을 방지. 즉 적절한 IDF 값을 가지게 하고 안정적인 결과를 얻을 수 있음

In [59]:
vectorizer = TfidfVectorizer(stop_words='english',
                        max_features = 1000,
                        max_df = 0.5,
                        smooth_idf = True,
                        )
X = vectorizer.fit_transform(news_df['clean_doc'])

X.shape

(11314, 1000)

## 5.LSA를 통한 토픽 모델링

In [81]:
svd_model = TruncatedSVD(n_components = 20, algorithm='randomized', n_iter=100, random_state=10)
svd_model.fit(X)        #UxS
len(svd_model.components_)      #SxVT


20

In [82]:
svd_model.components_.shape

(20, 1000)

In [84]:
svd_model.components_

array([[ 0.01409818,  0.04787982,  0.02051048, ...,  0.07483329,
         0.01377606,  0.01712888],
       [-0.00521437,  0.01742255, -0.01542793, ..., -0.06266609,
        -0.01075043, -0.01888594],
       [ 0.00243598, -0.00142246, -0.01848973, ...,  0.05823359,
         0.02412148,  0.02038499],
       ...,
       [ 0.00746824, -0.00689738, -0.00963879, ..., -0.03316437,
        -0.00649624, -0.0002525 ],
       [ 0.00352545,  0.01029423, -0.01284824, ...,  0.01336511,
        -0.01588696, -0.00127575],
       [-0.00221751,  0.00855739,  0.0062343 , ..., -0.0511237 ,
        -0.00794476, -0.00491316]])

- argsort() : 배열의 인덱스를 정렬된 순서로 반환 [3,1,2] -> [1,2,0] (오름차순 정렬)
- [::-1][:5] : 역순으로 정렬 후 5개의 데이터 선택

In [85]:
example_array = np.array([[0.1, 0.4, 0.2, 0.9, 0.3]])
print('argmax : ', example_array.argsort())

sorted_indices = example_array.argsort()[0][::-1][:5]
print(sorted_indices)

argmax :  [[0 2 4 1 3]]
[3 1 4 2 0]


- 주제0번에 대한 단어별 가중치

In [86]:
print(svd_model.components_[0].shape)
svd_model.components_[0]

(1000,)


array([0.01409818, 0.04787982, 0.02051048, 0.02933549, 0.01732167,
       0.01227351, 0.01648381, 0.01181282, 0.01084788, 0.0593574 ,
       0.01055266, 0.0111863 , 0.00867278, 0.03419897, 0.01132049,
       0.0401397 , 0.0177775 , 0.00850201, 0.03508718, 0.0158544 ,
       0.02076485, 0.01292826, 0.01060273, 0.01168965, 0.01392965,
       0.02813562, 0.0110224 , 0.00927105, 0.00607689, 0.0090752 ,
       0.03507546, 0.01364729, 0.01940152, 0.04266487, 0.01638954,
       0.0120186 , 0.01376949, 0.02842646, 0.02492808, 0.01559292,
       0.01259682, 0.021828  , 0.03209353, 0.01136994, 0.01236091,
       0.01826516, 0.01198612, 0.00833366, 0.03061078, 0.01221436,
       0.02441905, 0.02483554, 0.01177919, 0.00769201, 0.0165582 ,
       0.01614453, 0.01055487, 0.01213478, 0.03688943, 0.01293101,
       0.02388438, 0.02126642, 0.02266981, 0.01389217, 0.01078975,
       0.01070881, 0.01389446, 0.0098783 , 0.01064283, 0.01166813,
       0.05015364, 0.01938976, 0.01583951, 0.04028201, 0.01072

In [87]:
# 내림차순 정렬 후 상위 5개의 단어 반환 -> 0번째 토픽과 가장 연관성이 높은 단어 추출
svd_model.components_.argsort()[0][::-1][:5]

array([448, 483, 458, 626, 893])

In [88]:
(vectorizer.get_feature_names_out()[448],svd_model.components_[0][448].round(5))

('just', 0.20887)

In [89]:
# tfidf 벡터에서 어휘집의 인덱싱을 통해 0번째 토픽의 상위5개에 해당하는 단어들 확인해보기
(vectorizer.get_feature_names_out()[448], svd_model.components_[0][448].round(5))

('just', 0.20887)

In [90]:
(vectorizer.get_feature_names_out()[443], svd_model.components_[0][443].round(5))

('jewish', 0.01963)

In [95]:
terms = vectorizer.get_feature_names_out()    # 어휘집 : 1000개의 단어가 저장되어있음

for idx, topic in enumerate(svd_model.components_):
    sorted_indiced = topic.argsort()[::-1][:5]
    print("Topic %d" %(idx+1), [(terms[i], topic[i].round(5))for i in sorted_indiced])
    break


Topic 1 [('just', 0.20887), ('like', 0.20469), ('know', 0.19349), ('people', 0.18318), ('think', 0.1697)]


In [99]:
# 문서별 가장 관련성이 높은 (비중이 높은) 토픽 상위 n개를 추출하는 함수 생성

def get_document_topics(lsa_matrix, n=5):
    for idx, doc in enumerate(lsa_matrix):
        if idx == 10: break
        print(f"Document {idx+1}:", [(f"Topic {i+1}", doc[i].round(5)) for i in doc.argsort()[::-1][:n]])


# 문서벡터 행렬 생성
lsa_matrix = svd_model.transform(X)

# 문서별 토픽 비율 확인
get_document_topics(lsa_matrix, n=13)

Document 1: [('Topic 1', 0.12113), ('Topic 16', 0.11515), ('Topic 11', 0.06132), ('Topic 4', 0.03096), ('Topic 17', 0.01737), ('Topic 15', 0.01291), ('Topic 20', -0.00022), ('Topic 13', -0.00507), ('Topic 8', -0.00887), ('Topic 10', -0.00913), ('Topic 9', -0.01505), ('Topic 12', -0.01545), ('Topic 14', -0.02146)]
Document 2: [('Topic 1', 0.18497), ('Topic 5', 0.0606), ('Topic 20', 0.05117), ('Topic 4', 0.04349), ('Topic 6', 0.04149), ('Topic 13', 0.03836), ('Topic 18', 0.0264), ('Topic 19', 0.01761), ('Topic 14', 0.01354), ('Topic 7', -0.00813), ('Topic 12', -0.00956), ('Topic 11', -0.01125), ('Topic 3', -0.01723)]
Document 3: [('Topic 16', 0.21279), ('Topic 1', 0.15809), ('Topic 11', 0.09175), ('Topic 10', 0.06153), ('Topic 15', 0.0545), ('Topic 9', 0.02733), ('Topic 8', 0.0212), ('Topic 20', 0.01339), ('Topic 5', 0.00578), ('Topic 7', 0.00563), ('Topic 17', 0.00478), ('Topic 4', -0.01269), ('Topic 6', -0.01598)]
Document 4: [('Topic 1', 0.17093), ('Topic 8', 0.11107), ('Topic 4', 0.1